### ISSUE TITLE
Add RUST_LOG to .env and help text

### ISSUE THREAD

**Issue by CjS77** [tari-project/gh-pilot#81]
RUST_LOG=info,ghp_server=debug

See #79

**Comment by leet4tari** [comment]
Might be worth reduce ```/health``` feedback, or if there is a way to target remove health logging. Once the basic is setup an running, it is a little noisy.

**Comment by CjS77** [comment]
All endpoint accesses are logged, so we must either
* not log `/health` at all
* reduce the ping frequency from health check tools.

It should be fairly easy to filter out these lines from grafana if it's too noisy, but not logging at all feels like overkill.
